name = "gente-networking-lps"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "gente-networking-db"
database_id = "cef239b3-f4e8-4e03-acf1-48aef86c2829"

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "gente-networking-assets"
